### ISSUE TITLE
alter form interface sometimes has "extra" nodes

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#1025] opened 2020-02-20 19:03 UTC
From user feedback in slack:

Sometimes the alter form interface shows screens for "10 of 3" or "4 of 2" nodes. See these screenshots:
![Screenshot_20200214-135658_NetworkCanvas](https://user-images.githubusercontent.com/16093053/74968411-ca504e00-53e8-11ea-9b11-84c7f31ec2bc.jpg)

![Screenshot_20200214-141023_NetworkCanvas](https://user-images.githubusercontent.com/16093053/74968413-ca504e00-53e8-11ea-95bf-b69cc367067f.jpg)

It seems like this could be related to node filtering on the stage level, but checking values for the rules and predicates within networkQuery looked as expected and we have not successfully reproduced this yet.

The user also mentions issues with data not showing in the form if they navigate backwards in the interview, however it is not clear whether this was only for the nodes that shouldn't even be showing on the alter form stage.

Placing here so we can check into this further. Protocol is in slack.

**Comment by jthrilly** [comment] 2020-03-23 14:05
This issue may have been resolved by https://github.com/codaco/Network-Canvas/pull/1026, since this could conceivably have been caused by form name collision. We were unable to reproduce anyway, so closing now until we receive data to the contrary.

**Closed by jthrilly** 2020-03-23 14:05 UTC
Labels: bug
